### ISSUE TITLE
Check literature on event studies with overlapping events

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/min_wage_rent#11]
[Goal]
Understand what is the event study that we should do such that we use all data (including events that have some overlap). 

[Steps]
1. Search other papers that do an event-study with high frequency events. 
2. Report what they do and how and point to the sources.

**Comment by santiagohermo** [comment]
I got comments from the boss: [annotated-Breakfast_Feb2020.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/4341173/annotated-Breakfast_Feb2020.pdf). He proactively asked for the slides and sent them, which is great! (I had mentioned @gabrieleborg's presentation).

I am going to tell him the data issues we encountered (coding error in the slides figure, moving average, etc) and ask him about this problem specifically. I can suggest to meet (via zoom I guess) in a couple of weeks once we thought this through. What do you think @diegogentilepassaro @gabrieleborg ?

**Comment by santiagohermo** [comment]
Today we will be having a Zoom meeting with Jesse. These are the e-mails that led to it: [mails.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/4350290/pre-meeting.jesse.pdf)

I will copy a summary of his suggestions in this issue later.

**Comment by santiagohermo** [comment]
Jesse's comments @diegogentilepassaro @gabrieleborg (feel free to edit/add stuff):
- Prices and rents are very different. Prices = present discounted value of rents. They don't necessarily move together.
   - House prices should change when information is revealed.
   - House prices will be a random walk at a first approximation. (they are an asset price!). Fixed effects will be less efficient than first differences models.
   - Careful about deterministic trends, can be messy with stochastic trends.
- No robust solution to deal with overlapping events.
   - Advice: think of a structural model as a first approximation.
   - Be aware of wrong estimation of fixed effects due to timing.
   - Problem: take a stand on using formerly treated units as controls for newly treated ones.
- Start with a first difference version of the event study (before moving to something more structural).
   - Simulate series to try out the estimation.
   - Estimate on two different samples with zipcode with many MW earners and zipcode with few MW earners.

**Comment by santiagohermo** [comment]
Per meeting (and after Jesse's comments on not being a clear way to deal with this) we will close this issue. We will focus on data construction and discuss the identification strategy in later issues.
