### ISSUE TITLE
Uncover Zillow Index Methodology

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#13]
**Goal**
Have a clear understanding on how the Zillow variables are built, what they measure, how they can be used and what's the value for our study

**Steps**

1. Read and download Zillow methodology files
2. Figure out the best potential variables for our designs, and why. 
3. Report exactly what the variables are, and  how they are computed.
4. Think and report potential consequences of the variable build on our computations.

**Notes**
1. Smoothed (moving averages) variables should have a progressive dynamics when impacts are discrete. Jumps on impact shouldn't be possible. 
2. Maybe a follow-up task, once we understand what we are going to use, would be to perform Montecarlo simulations to understand the impact of smoothing on a toy series that resembles the data.
3. Think about seasonally adjustments in the y variable.

**Comment by santiagohermo** [comment]
There is a lot of information in [that file](https://github.com/diegogentilepassaro/min_wage_rent/issues/13#issuecomment-599603633) @gabrieleborg. So much so that I think we should include it either in the repo or google drive folder. What do you think @diegogentilepassaro ?

Zillow is doing a lot of things to the raw data to obtain those indices. I think our main results should not come from them, the moving average is kind of a killer! Rather, we should use Zillow's raw data (and other sources). For example, the `InventoryMeasurePublic`, `MedianListingPrice` and `MedianRentalPrice` look promising. Of course, we should try the indices anyway to make sure the results are as expected (they should look like the main results but attenuated, right?).

Question: do we have access to the data on "market segments" that you mention in the file?

Regarding the formatting:
- I can't open links from the file. I think it's because overleaf modifies them (e.g., https://www.overleaf.com/project/5e6a9dfb1a5a40000198775a#https://www.zillow.com/info/whats-the-zillow-home-value-index/)
- Sometimes there are question marks. Is that you not being sure of what Zillow did or some broken reference?

Thanks again!

**Comment by gabrieleborg** [comment]
Hi @santiagohermo sorry for the delay. I agree in that we should eventually use raw measures such as median prices or rents. I think we could keep the indexes as robustness check to validate some assumptions (e.g. assumption regarding seasonality or those things we know are addressed in the index construction). 

Yes, we do have data on different market segments. These are simply the combination between property type (as classified in the pdf as well) and different number of bedrooms. 

Question marks are my personal doubts. I left them when I couldn't properly understand what was going on!

**Comment by gabrieleborg** [comment]
Right now I am working on creating some descriptive stats for all Zillow series

**Comment by santiagohermo** [comment]
Thanks for [those answers](https://github.com/diegogentilepassaro/min_wage_rent/issues/13#issuecomment-600759281) @gabrieleborg! Looking forward to seeing the results of your descriptive stats!

**Comment by gabrieleborg** [comment]
Steps 1, 2 and 3 completed. I have created a script that uses the temporary output 'data_clean.csv' produced by https://github.com/diegogentilepassaro/min_wage_rent/blob/f8f2b89e07b2880d5fb7b5c2328b50f725f20073/derived/code/addMinWage.R#L24

The script returns two outputs: 

1. A descriptive table for all Zillow series present in the  input dataset;
2. A collection of plots, one for each Zillow series showing the time trend evolution of the mean value

### Descriptive Table 
There are still few issues, and the code can be optimized. Happy to accept suggestions! In particular, for some reason I haven't figure out yet the save_data function doesn't work. For now I am using fwrite. Furthermore, descriptive statistics, number of observations and missings are based  on the time window Jan2010-Sep2017 for all series whose first ever observation is in that period (few older series instead start in 1996. You can easily spot that by looking at the column N) : https://github.com/diegogentilepassaro/min_wage_rent/blob/f8f2b89e07b2880d5fb7b5c2328b50f725f20073/analysis/code/zillow_descriptive.R#L117

The table reports the following statistics for each Zillow series: 

- totNA: number of zipcodes with no observations at all

- tot_zip: number of zipcodes with at least one observation

- N.mean/sd/median/min/max: standard stats on the zipcode-level time series length

- EventPerZip: average number of events (identified by changes in max min wage) per zipcode 

- N: total number of non-missing observations 

- mean/SD/min/max: standard stats on the Zillow series value


### Zillow Series Plots 
The plots contained in [plots.pdf](https://github.com/diegogentilepassaro/min_wage_rent/blob/issue13---Uncover-Zillow-Methodology/analysis/output/zillow_plots.pdf) report, for each series, the evolution of the average value along with a 95 percent confidence interval.

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! I noticed I need to build everything to reach to see the table, which is kind of annoying. So, in the process of reviewing your analysis I am going to modify the pipeline a bit as we discussed in past meetings. Specifically, I am going to:
1- add derived and derived_local,
2- add your [pdf](https://github.com/diegogentilepassaro/min_wage_rent/issues/13#issuecomment-599603633) to the pipeline,
3- separate output in "descriptive" and "event-studies"

These changes are not huge so I think it's cool to do them in this branch instead of opening a new issue. (Let me know if you disagree!)

**Comment by gabrieleborg** [comment]
Sure @santiagohermo , go ahead :)

**Comment by santiagohermo** [comment]
Btw @gabrieleborg, the function in R doesn't work because the packages it uses are missing from the lib file. I'll fix that as well. Thanks!

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro  In light of https://github.com/diegogentilepassaro/min_wage_rent/pull/19#issue-391938964 do you want to merge this before #18, and possibly start another issue regarding the "comparison with other indexes" ?

**Comment by santiagohermo** [comment]
That sounds reasonable @gabrieleborg. We could also wait until #19 is merged and update this branch. I'm indifferent really!

**Comment by gabrieleborg** [comment]
makes sense! Ok let's close #19 if @diegogentilepassaro it's ok,  and then let's update and merge this as well

**Comment by santiagohermo** [comment]
In light of @diegogentilepassaro's review I'm making a couple of changes to #19. I will over soon (I have to wait until derived runs!). If diego has time to re-review today we will merge back and you can update here. 

I think these changes will speed up our work in the future (specially saving output from derived online), so thanks for the patience!

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg you are clear to move forward on this one :D

I haven't had time to review everything carefully but I will do so when this in PR! Great work @gabrieleborg !!!!

**Comment by santiagohermo** [comment]
Feel free to update the branch and organize your work in `analysis/descriptive` @gabrieleborg. I will review later.
