### ISSUE TITLE
Check data construction for geo codes, balance panel, fix event-study methodology

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#24]
**[Goal]**
As per April 01 2020 meeting, address the remaining methodological issues regarding the panel construction. In particular, make sure that our baseline panel(s) are composed of a set of fixed geo codes over time, such that for each geo code we have certainty of the county and state that it belongs so that we can assign information on MW changes.  Then re run analysis re-thinking event study methodology. 

**[Steps]**
1. Explore why there were some zipcdodes without MW change data as pointed out [here](https://github.com/diegogentilepassaro/min_wage_rent/pull/23#discussion_r403771596). 
2. Reassess the geo unit assignment in general. Consider mapping zipcodes to census tracts first if that helps. 
3. Make sure that each zipcode has assigned at least one and only one county. Each county then will have assigned a unique state.  Some zipcodes will belong to a MSA, the rest should be either in small places, or rural. We should probably find data on that distinction. 
4.  Create balanced panel(s) by actively selecting zipcodes with a populated enough time-series (e.g. all zipcodes with a fully populated time-series starting in 2012).
5. Re run analysis for baseline panel(s) re thinking through our event study methodology.

**Comment by gabrieleborg** [comment]
Update: 

In commit 71287027e94651c6dc7ee5cc7b700f03327746d0 on related branch I address the issue of events too close to the dataset boundary (conditional an event window size) by _dropping_ events that are too close to it (see analysis/event_study/code/preclean_event_studies.do). 

This however made me think more broadly about our methodology as implemented in the present form: 

- There is still a confounding event effect in the post-dummies for the new last event: e.g. If I if I ignore Jan 2019, then the Jan 2018 event will have a confounding effect in the t+12 dummy)

- In general,  I suspect yearly changes in min wage are responsible for those not so smooth pre-trend as well as little jumps: e.g. if you look at the Jan 2018 pre-trend, that's technically the Jan 2017 post-trend as well (and indeed you see a little jump and an increase before stabilization around 6 months in).

- The best solution for last event maybe it's to restrict the event window to 11 months, so we don't capture the next or previous event.

- This in general could help also the clean pre-trend specification as well: in the 12 period specification we're throwing away many events when there are changes every year (e.g. in NYC they start in 2014, but we throw away all changes but the first one. For this reason I added a minor change here: https://github.com/diegogentilepassaro/min_wage_rent/blob/71287027e94651c6dc7ee5cc7b700f03327746d0/analysis/event_study/code/preclean_event_studies.do#L77
now we are keeping events that, despite having an overlap window in theory, they don't have it in prectice as we are already discarding the previous event: e.g. suppose we have changes in Jan 2015, jan 2016 and Jan 2017. Before we were keeping only Jan 2015 event. Now we are keeping Jan 2015 and Jan 2017 since we are ignoring Jan 2016. Notice that we are still mantaining our basic assumption of having clean pre-event windows.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg, as for the discussion of how to fix the last event methodology it seems that there is no clear solution so far and going with windows of 11 is a temporary hack to be sure that were are doing things correctly. 

Once you commit that and the balancing of the panel let me know and I will tackle #26 after a quick PR here. 

Thanks!

**Comment by santiagohermo** [comment]
I was reading Dube et al (QJE 2019) and I found something interesting @gabrieleborg @diegogentilepassaro for this issue: how they treat minimum wage changes that are excluded from their main definition of an event. From my first read is not clear to me how they treat 'overlapping events'.

Two key things to look at from the paper:
1. Page 1415, in particular this footnote:
![image](https://user-images.githubusercontent.com/45404755/79028660-f4a7c780-7b5e-11ea-869a-43d70abeb730.png)
They directly control for excluded MW changes in their regression.
(BELOW and ABOVE are dummies for wage observation being above or below MW. Not relevant in our case)

2. Figure 1.A in [online appendix](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/qje/134/3/10.1093_qje_qjz014/4/qjz014_supplemental_online_appendix.pdf?Expires=1589585327&Signature=QwWV9ZUBGNLwT4Pc~6QeA0y88VyMA5mbGfVHpfNBJxSkWonb0lbAMkmD10vCvoEtAwwmkuq~KezoRaAYGBMjYifn1gNk~WRKYnK64FkHKSTCXzw6o9MSoWp53Di-XQs3U2cA3HXjTJJpipjzbMVzmY8qpO~uI0b5GS9SToBvdULuzxX7MeKnQ7YxyZHUsy6CivEWC8jLDAOFdmJIM9yt3cXwasqPwa6iAmedGiMIN17Q23ESMMFfT1H-mHgwJ3e6REcfc9laaAKAod9dYv1H9lGdbW9vOxfwR5xHZdZ6iHBygGbAo4TXU6fUCGqiNFvPAdBvCcGOLKMLqtch-vwJ2A__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA).

<details>
<summary> See figure </summary>
<p>

![image](https://user-images.githubusercontent.com/45404755/79029407-4736b300-7b62-11ea-9781-559c5e7738b8.png)

</p>
</details>

They use events in blue. Clearly, there must be overlapping in their sample.

This made me thing of two issues that I think are appropriate to address here:

#### 1. On events we don't use
We are excluding a lot of events in our last event methodology. I think it makes sense to add to it similar dummies to dube's paper for all the MW changes that we are not using. Let me explain why.

One theory on what is happening to our plots is the following. So far we are ignoring a lot of MW changes. Since most of them happen in January or July, they likely confound our calendar-month fixed effects which may be biasing our coefficients of interest. So adding these controls may help to fix the plots.

#### 2. On overlapping events.
As far as I read, dube et al don't care about the fact that some events are overlapping. So how do they implement it? We are creating the relative months variable and adding dummies automatically with `i.var`. When creating the relative months variable we don't know how to treat windows for overlapping events. However, if we instead create the dummies explicitly this issue won't arise, as the period -6 of a MW change will also be the period +6 of another one as reflected by the dummies. See what I mean? 
I am not sure what this does to the parameters though, and maybe there is a critic to be made to dube et al?

One way to deal with this would be to redefine the event. Instead of looking at the effect of a single jump in minimum wage, why not think about the effect of successive regular changes in MW in a given X years period? Our event definition would include the indexing, and I presume could be correctly estimated given the large number of MW changes available. It seems a valid question to ask as well.

**Comment by santiagohermo** [comment]
If you guys think the steps I outlined above are worth pursuing we can keep this issue open a bit longer and @diegogentilepassaro can start #26 branching off of master directly.

**Comment by diegogentilepassaro** [comment]
Great discoveries @santiagohermo! 

I totally agree with 1. 

As for 2., I understand why creating the dummies directly can help: same observation will have a 1 turning on for ALL of the dummies of the different relative times that correspond to that moment. I think this is a clever idea, and potentially a good hack. I am happy to give it a try and see what happens, but as you mentioned I also don't know what is the consequence of doing this for estimation. We will have to think about it and ask Jesse for advise. 

Also, the steps that you propose sound good to me, but please let's first balance the panel so that we start closing frontlines of problems. Also, doing that will help me to understand how to do #26 without writing a separate chunk of code balancing the panel that we will then have to figure out how to mix together!

**Comment by diegogentilepassaro** [comment]
@santiagohermo @gabrieleborg if you guys don't have a problem with it I will take over this task and:

1. Balance the panel for a fix set of zipcodes.

2. Implement the steps that @santiagohermo lays out [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/24#issuecomment-612270313). About this I am not sure about how to control for other events that are small or overlap but I will give it some thought and I am happy to discuss. 

I am happy to discuss also if you guys believe that there is a better way to do this :D

**Comment by gabrieleborg** [comment]
Thanks @diegogentilepassaro , that is fine for me :)

I just pushed commit fa56ce9fbcbdaf0eec94108bc12934cdba2cd0fb where I experimented with a couple of panel balance event methodology: 

1. For a given time window (e.g. Jan2012 - Dec2018), and for each dep var separately, I select only zipcodes that have the full time series. 

2. For a given time window, select only time series with more than x periods. In this sense, we could select fairly homogeneous time series for each zipcode, being sure they fall within the desired time-window. I am not entirely sure which benefits this could have over the first methodology, but I felt that this could give us some power in situations where there aren't many fully-populated zipcode level time series? This comes after the study of the different series that we have., since For all places there seems to be no series with holes in it. In addition here is the distribution of series length for medrentprice_sfcc:
![image](https://user-images.githubusercontent.com/30894427/79385870-47a2c580-7f37-11ea-8d86-b12ac173efee.png)

In order to maintain flexibility in the analysis, the prepare_data subprogram in preclean_event_study creates a series of indicator variables selecting the desired sample for each depended variable we want to use. In this way, say we want to run the "only last" event study methodology on medrentprice_sfcc, choosing the fully-balanced sample, we just set the parameter `panel_bal== "fb"` (full balance) in the first_last_event_study dofile. The ado file now automatically filter observations based on the sample selected (i.e. I added a if `fb_varname` to the regression command). 

I don't know whether keeping track of all possible balanced sample keeping indicators in the main panel is efficient, but I am open to your suggestions! In this way however we can also compare characteristics of the different samples to see, for example, which one is exploiting more observations, which one has the more zipcodes etc. 



As per @santiagohermo message, I read the Dube methodology and I agree that we should try, and especially we should try to identify a set of events we want to exclude and capture them with a dummy! My feeling here is that we have to be careful in choosing events based on conditions that are not related to the relative time with repsect to another event, otherwise we would get biased pre- or post- dummies. does it make sense?

**Comment by diegogentilepassaro** [comment]
Thank you for your work @gabrieleborg! The code looks great. I will take a look to the different possibilities, make sure it runs, and will start exploring some specifications to see how things look.

Will update when I have something meaningful.

**Comment by diegogentilepassaro** [comment]
@gabrieleborg just tried to run the code as it came and I get the following error in substate_mw.do
![Screen Shot 2020-04-15 at 6 49 21 PM](https://user-images.githubusercontent.com/20582494/79396455-fcde7900-7f49-11ea-8228-a98a41ac18fd.png)

Any clues?

**Comment by gabrieleborg** [comment]
Sorry it was a column I tested and forgot to remove eventually. Once we'll tackle the scheduled increases in minimum wage issue we'll figure out the best way to handle it. I updated the file, you're good to go!

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! I think it is a great idea to keep an indicator to select the sample. The alternative would be to manually select the sample before running the event study, which code-wise seems much less clean.

The [current output](https://github.com/diegogentilepassaro/min_wage_rent/tree/fa56ce9fbcbdaf0eec94108bc12934cdba2cd0fb/analysis/event_study/output) doesn't seem as weird as before, but in many of the plots there is no effect. I'm looking forward to see how those event studies corrected _a la_ Dube with larger windows look like!

Small thing: could you tag the issue number in your commits so that it easy to access them? Thanks!

**Comment by diegogentilepassaro** [comment]
Thanks @gabrieleborg! I will start my exploration :D

**Comment by diegogentilepassaro** [comment]
Also @santiagohermo: I see quite an effect [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/fa56ce9fbcbdaf0eec94108bc12934cdba2cd0fb/analysis/event_study/output/medrentpricepsqft_sfcc_last_mw_event_rel_months11fb.png)  and [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/fa56ce9fbcbdaf0eec94108bc12934cdba2cd0fb/analysis/event_study/output/medrentpricepsqft_cc_last_mw_event_rel_months11fb.png) using the last event with full balance which seems to me like the ones we can rely on at this point. I am looking at the wrong plots?

**Comment by diegogentilepassaro** [comment]
@gabrieleborg I don't see the new commit on this branch. Are you sure you have committed?

**Comment by gabrieleborg** [comment]
I just deleted manually from the file! I know we should do it, but it was basically empty because i didn't add almost anything to it.

**Comment by diegogentilepassaro** [comment]
All good @gabrieleborg! However the code still doesn't run :/ 

Should I go ahead and delete all calls to that variable in the code?

**Comment by gabrieleborg** [comment]
sorry, yes



*-Gabriele N Borg*
Department of Economics,
Brown University
Providence, RI 02912

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg note that I have broaden this task and I have modified the task description accordingly.

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg I have a first pass for some major changes in this task. Fortunately, I believe that overall the news are very good. 

Let's start with some comments about what I've changed respect to @gabrieleborg's commit on this issue:

- I have moved the balancing of the panel to derived as I thought we agreed.. There I output two balanced baseline panels (one for the rent variables and one for the listing prices), and one panel with all zipcodes months as we had before. I left this last as legacy for now, as I don't see how we can possibly use it in the short term, but eventually this panel should converge to the one in where we host our robustness samples. The benefit of having lite clean baseline panels is that the analysis code runs much much faster (go ahead and try yourself for fun :D). Also, now the windows are 12 and 24 and things look pretty good for the main outcomes (see below in in conclusions for more detail).

- As for the balancing of the panel several comments. First, I have confirmed that once a zipcode is in the data stays for ever and I have used that o make the code balancing the panel very short., the number of zipcodes in which we have zillow dates changes by the variable. Therefore, when I say balanced here I mean that the set of zipcodes that appears on the panel is fixed for a given variable. In the end, I constructed a baseline panel for rental variables, and another for listing prices. For the rental panel I used as *date*=January2013 for the listings I used *date*=Jan2010 The way I constructed them was as follows. 
  1. For each rental variable I counted the number of zipcodes that had data as of *date*.
  2. Then I created a balanced panel of zipcode-months until December 2019 from the variable that had the max number of zipcodes. 
  3. Then, I merged the data for the other variables **ONLY** for the zipcodes that had data in *date*. This way we don't populate the zipcodes that started to have data after *date* that are part of the set of zipcodes that corresponds to the max. Note that this implies a different number of observations for each variable. 

- I have cleaned up a substantial part of derived that was never used in analysis. Now it runs in around half of the time. 

- I have modified the function create_event_plot to m for some optional plotting options, and I have removed the balanced panel option as it is confusing with the new baseline panels, and it is a good idea to keep our main function as abstract as possible. 

- I have changed the last event study methodology so that now for a given window we use events that have at least window+1 periods of data after the MW event. Also, for a given window it creates a variable that is the cumulative number of unused MW change events, I use that as a control in some explorations. 

- I have created in analysis a folder called test_event_study that play around with specifications and produce some plots aimed at understanding the consequences of the different sets of controls (including the cumulative number of unused MW changes). Below the results for medrentpricepsqft_sfcc when adding progressively more controls
![Screen Shot 2020-04-18 at 9 39 40 AM](https://user-images.githubusercontent.com/20582494/79639274-d5a9c680-8158-11ea-9749-9a6cca00a8e6.png)
and for medlistingpricepsqft_sfcc:
![Screen Shot 2020-04-18 at 9 40 01 AM](https://user-images.githubusercontent.com/20582494/79639285-ece8b400-8158-11ea-9f02-14e249e5db88.png)

Now, let's go to the fun part: some preliminary conclusions.

- Once the panel was balanced and we shutdown zipcode composition effects, and we forced our code to use events such that there is at least as many data points in the panel as there are periods in the post window, the event-studies for windows of size 12 or 24 look pretty smooth and there are no weird jumps. See for example [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/issue24-fix-last-event-methodology/analysis/event_study/output/medrentpricepsqft_sfcc_last_sal_mw_event_rel_months24.png).

- It seems that different sets of controls don't change much our answer unless we basically kill variation at the level of most of our MW changes (state-year-month).

- Bumpiness: seems that it was a consequence of 3 things. First, unbalanced zipcode selection. Second, using events without enough data in the post period. Third, and the most surprising, controlling for state-specific calendar months. My intuition is that we are asking to much to data because most of our MW changes are at the state level so when trying to identify both the state-specific calendar months and the dynamic coefficients with only one change per zipcode it is just not possible. Instead when we use county-specific calendar months they are less problematic because different counties have different seasonalities around a state MW change. The good news, is that with only zipocde and year-month fixed effects we do very well, all plots are very smooth. We should probably have those as our baseline for now. 

- Controlling for unused MW changes doesn't do much although I controlled for the cumulative number of unused MW changes only because intuitively this is what will cause level shifts in 6 or 12 months periods. Our results are robust to this. We can think of other ways of controlling as per @santiagohermo comment. Intuitively, we could control for the cumulative amount of the unused MW changes or something like that. 

What is left on my end:

1. Check geo codes. Presumably we will gain a little sample size when we nail that down so I don't expect much changes in the plots. 

2. Do some first stage plots. See how the value of MW change around a change. This will allow us to know how much is the average change that we are using as an event and we will be able to do back of the envelope calculations like: pass through is x% of the average MW change. Probably our figure 1 should be a panel with the first stage above and the event study below for our preferred variable (so far medrentpricepsqft_sfcc). We should create this figure and put notes as if we were going to include it in the paper now.

3. Start thinking about using the overlapping events in the terms that @santiagohermo described. Probably, we should do this as part of #25. 

Things to do on your end:

1. Get familiar and review carefully my code. I think that we can conclude that our last event study methodology is done, so make sure that you agree with me and that there are no code or conceptual mistakes. 

2. Play around with the different sets of controls and specifications and think about my comments above. 

@gabrieleborg some comments about your code:

1. The code on your last commit did not run as you can see in make.log [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/fa56ce9fbcbdaf0eec94108bc12934cdba2cd0fb/analysis/event_study/output/make.log)
![Uploading Screen Shot 2020-04-17 at 9.47.43 PM.png…]()

2. In your comment you said that your dates for balancing the panel were January 2012 to December 2018. But in as you can see [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/fa56ce9fbcbdaf0eec94108bc12934cdba2cd0fb/analysis/event_study/code/preclean_event_studies.do) your code they were January 2013 to November 2018 (as your code had a less than Decemeber 2018). The end date now is December 2019, as we have that data, but as for the start date I went for January 2013 because it had slightly more zipcodes. Also, from reviewing the code it was not clear to me what concept of "balancing" you were trying to implement, but let me know if what I have implemented makes sense given what you had in mind and we can keep discussing. 

3. I have deleted several code-comments that were legacy or part of your exploration.

**Comment by gabrieleborg** [comment]
Morning @diegogentilepassaro and @santiagohermo ! sorry for the late reply, but here is my review of Diego's work: 

- The code looks good to me. Good performance improvement. I think it's clear and needs no editing. 

-  > iii. Then, I merged the data for the other variables ONLY for the zipcodes that had data in date. This way we don't populate the zipcodes that started to have data after date that are part of the set of zipcodes that corresponds to the max. Note that this implies a different number of observations for each variable.

      Just to clarify: when you say "note that this implles…" you refer to the fact that, despite starting all at date, each zipcode time-series might have different length due to different end dates(e.g. zipcode1: Jan2013 - Dec2015, zipcode2: Jan2013 - Dec2019)?

- > I have changed the last event study methodology so that now for a given window we use events that have at least window+1 periods of data after the MW event. Also, for a given window it creates a variable that is the cumulative number of unused MW change events, I use that as a control in some explorations.

     Why are we selecting events that have at least window + 1 periods after the MW events, as opposed to window? From what I remember when we say, for example, a 12-months window we mean that we want to have 12 months before and 12 months after the event, for a total of 25 months. Is it to account for the possible next MW increase?

- The event study plots looks good, nice job Diego! That  shows the power of balancing the panel. For what I can see, we are left with a slight seasonality in the post-event dummies. I wonder whether  it may be some market seasonality related to rental renewal (i.e. landlords raising price). There could be many properties rented by students and this would bump demand in summer/September? I wonder whether the fact we do have that kind of patterns could reflect in the first place  that we probably have many events in January, and therefore that bump could indeed match summer months, but at the same time it doesn't match that exactly for calendar month FE to properly control for it?.  In general I'm wondering whether wage increases match rent-renewal periods. Here I find some (not very technical) references to that: [link1](https://www.investopedia.com/articles/real-estate/090116/when-best-time-rent-apartment.asp) [link2](https://www.renthop.com/studies/national/best-time-of-year-to-rent).  The fact that calendar FE don't kill that makes me think that it's because maybe seasonality is more local, but at the same time it doesn't happen in every place in the same months (i.e. student places in August and September, while maybe more working places more around May June?) I'm wondering whether we could find some instrument Jesse-style that is not related to MW changes that can plausibly control for that. In the _Pre-event Trends_ he mentions using adult employment an studying it's dynamics around MW changes to control for unobserved labor demand. What about trying to replicate something similar in the context of the housing market, meaning we actually look at listing price of houses that reasonably are not in the rent market (e.g. high-end) but that nevertheless can track the market in the first place?

**Comment by diegogentilepassaro** [comment]
Good morning @gabrieleborg! We talked about your comment in out last meeting but just for the record I forgot to add my answers. Here they are:

> Just to clarify: when you say "note that this implles…" you refer to the fact that, despite starting all at date, each zipcode time-series might have different length due to different end dates(e.g. zipcode1: Jan2013 - Dec2015, zipcode2: Jan2013 - Dec2019)?

The answer is no! The dates are all the same for all series Jan 2013 to Dec 2019. The difference between series is the constant number of zipcodes in each of them. This is because I use the zipcdes that were available as of Jan 2013, and those are different for each series. This implies that one has to be careful because some zipcode enter some series later than Jan 2013, and we don't want to use them (if we want to keep zipcodes constant within a series) even if they were part of some other series in Jan 2013. In that sense, the panel was not holding zipcodes fixed before I modified the code. 

> Why are we selecting events that have at least window + 1 periods after the MW events, as opposed to window? From what I remember when we say, for example, a 12-months window we mean that we want to have 12 months before and 12 months after the event, for a total of 25 months. Is it to account for the possible next MW increase?

Say that the last two events for a certain zipcode are in December 2017 and December 2019. When you compute the variable `months_until_panel_ends = Dec2019 - year_month` you are going to get for observations in December 2017 a value of 24. Suppose that you want to use a window of size 24. Then, you might think that the event you want to use as the last event is the one corresponding to December 2017. However, that would be wrong, because the model we are running has 25 coefficients for the window (the event, 24 before, and 24 after) and 2 more coefficients: one for before the window and one for after the window. If you don't keep at least 1 more month than the post event window size, you don't have observations to estimate the "after the window" coefficient and the model will not be properly saturated. In fact, for zipcodes with the issue I just described you will think that the omitted category is -1 but will actually be a combination of -1 and post window.

**Comment by gabrieleborg** [comment]
Great, that make sense. Thanks @diegogentilepassaro

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg, I just finished a sizable commit implementing two things:

1. I wanted to answer the following question: How big are the used and unused MW changes around the used events? For that I computed the same event studies as before but were the dependent variable is dactual_mw. Note that for each window size the used events are different and so the event study of the MW changes also is. I then combined the event-study about the MW changes with my favorite outcomes. For the rent that was merentpricepsqft_sfcc and for the house prices was medlistingpricepsqft_sfcc. The plots live in analysis/event_study/output and they look like:

*Rents*
![Screen Shot 2020-04-30 at 1 50 49 PM](https://user-images.githubusercontent.com/20582494/80742606-a9436200-8ae9-11ea-8e36-3848f790d18d.png)
![Screen Shot 2020-04-30 at 1 51 10 PM](https://user-images.githubusercontent.com/20582494/80742618-acd6e900-8ae9-11ea-8484-979fbbc1377f.png)

*House prices*
![Screen Shot 2020-04-30 at 1 52 05 PM](https://user-images.githubusercontent.com/20582494/80742731-ddb71e00-8ae9-11ea-9ea1-e631bd0a7123.png)
![Screen Shot 2020-04-30 at 1 52 12 PM](https://user-images.githubusercontent.com/20582494/80742738-e0b20e80-8ae9-11ea-95a6-d2aa6001ea10.png)

Some interesting things to notice:
 
- The set of events used when selecting the last event using 12 months windows ends up having really big unused events 12 months before the event both for the rent and for the house prices. In both cases. In the case of the rents the unused changes 12 months before the event are bigger on average than the used events: the former is of around $0.9 and the latter of around $0.7. That's weird and unexpected but is possible so it doesn't necessarily mean a code mistake (although we should carefully check that).

- For the 24 month window in the rents baseline panel we can see that the average change used is of about $0.95. Using this number as a base, we can figure out some basic notion of the magnitude of the effects that we are finding. Below my rough reasoning for assessing these. 

> First, in a family of 2 MW earners that work each 40 hours a week that means a monthly extra income of 0.95x(2x40)x4.35 =~ $330 (where 4.35 is the average number of weeks in a month). 

> Second, I searched for the average number of square feet of a single-family house for rent. I couldn't find that exactly. [Here](https://www.census.gov/construction/chars/highlights.html) there are some very useful numbers for newly built homes although not sure if they will end up being the ones we use. Other sources ([here](https://www.quora.com/What-is-the-average-house-size-in-America), [here](https://www.aei.org/carpe-diem/new-us-homes-today-are-1000-square-feet-larger-than-in-1973-and-living-space-per-person-has-nearly-doubled/), and [here](https://www.census.gov/const/C25Ann/sftotalmedavgsqft.pdf)) seemed useful too. For simplicity now sat that the number we are after is 1500 square feet, but it looks that it could plausibly be between 1000 and 2000. 

> Our estimated effects imply a $0.015 per rented square foot on impact, about $0.025 six months after the MW change. Then we can make the following table:


| Assumed avg square footage for SF rented home  | Estimated effect for $ per square foot | Total rent increase | Implied pass-through|
| ------------- | ------------- |
| 1000 | 0.02 | 20 | 6.06%|
| 1500  | 0.02l 30 | 9.09%|
| 2000 | 0.02 | 40 | 12.12%|
| 1000 | 0.025 | 25 | 7.57%|
| 1500  | 0.025 | 37.5 | 11.36%|
| 2000 | 0.025 | 50 | 15.15%|

All this effects seem reasonable, as the average share of expenditure in rents should be of around 25-33%. Note also, that the unused MW change 12 months after the used one is of about $0.5, so that we should expect effects half as high. Well indeed the increase form month 11 after the used event to month 17 is of about half of $0.25. 

2. The second thing that I have implemented is some robustness with respect to the size of the used MW events. Remember that in the baseline we are using events with MW changes of at least $0.5. I have committed code under analysis/event_size_robustness that does the same analysis but for events of at least $0.25 and for events of at least $0.75 for both windows of 12 and 24. Results below:

*Rents*
12 month windows:
![Screen Shot 2020-04-30 at 2 35 57 PM](https://user-images.githubusercontent.com/20582494/80746564-15c15f80-8af0-11ea-8ab5-309f98684679.png)
![Screen Shot 2020-04-30 at 2 35 36 PM](https://user-images.githubusercontent.com/20582494/80746585-1ce86d80-8af0-11ea-95c0-dc05a717e1d0.png)

24 month windows:
![Screen Shot 2020-04-30 at 2 39 32 PM](https://user-images.githubusercontent.com/20582494/80746803-76e93300-8af0-11ea-8345-3a20e576ea59.png)
![Screen Shot 2020-04-30 at 2 39 42 PM](https://user-images.githubusercontent.com/20582494/80746811-781a6000-8af0-11ea-9779-c46b4a986663.png)

*House prices*
Look for them in the repo!

The thing to note: results are remarkably robust when properly scaled by the average size of the used MW change in each case! I didn't re do tables for this cases because they are really the same as before up to scale! Note that there is nothing mechanically about this as the events that are used for each zipcode in each case are different (as we pick the last that is at least some size). 

I think we are in a pretty good place now, we should have a meeting and we should maybe have a nice beer :D

**Comment by diegogentilepassaro** [comment]
More updates guys! I let myself go today and had so much fun working on this project. 

I have implemented under analysis/bootstrap_passthrough a rough computation of the passthrough and I have bootstrapped its standard errors resampling the whole time series of zipcodes. For the computation that I have committed I assumed a household with 2 minimum wagers that work 40 hours a week each, and an average rented home size of 1500 square feet. I produced a paper quality table that outputs the results for 100 repetitions. The passthrough was computed as:

`passthrough = (home_size *avg_effect_psqft)/increase_sf_income`

Where `home_size = 1500`, and `avg_effect_psqft` is the average of the 25 post event coefficients of the last event relative variables for medrentpricepsqft_sfcc in our baseline regression.  Define \Delta MW = the coefficient on impact of dactual_mw (the coefficient of 0 in the panel below of [this plot](https://user-images.githubusercontent.com/20582494/80742731-ddb71e00-8ae9-11ea-9ea1-e631bd0a7123.png)), then `increase_sf_income = \Delta MW (2x40x4.35)`. The table with the bootstrapped  95% confidence intervals looks like and lives under \draft\mw_rent_amenities.tex (so we have a tex file for start writing the draft too!):

![Screen Shot 2020-04-30 at 8 45 44 PM](https://user-images.githubusercontent.com/20582494/80772941-5a67ed80-8b26-11ea-994e-e1285b21b0cb.png)

The estimated passthrough, the estimated average effect on price per square foot, and the increase in single family income look all pretty nice! The passthrough is reasonable, pretty tightly estimated, and really significant!!!! 🥇

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg 
Update: I have made the table nicer, run 200 reps, and added a new statistics showing the total effect on monthly rent, the number of zipcodes used, and the number of bootstrap reps. 
![Screen Shot 2020-05-01 at 1 45 10 PM](https://user-images.githubusercontent.com/20582494/80827703-36ea8480-8bb2-11ea-88d6-362fc7e3ac33.png)

**Comment by diegogentilepassaro** [comment]
As per meeting I am not doing the update of the geo codes now and I will send this task to peer review.
