### ISSUE TITLE
Add all events specification

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#25]
**Goal**
Add an event-study methodology that keeps, for every zipcode, only events that have non-overlapping windows for a given window-size. 

**Steps**

1. Write the code

**Notes**

- Think about saturation: how do we deal with periods outside events' windows? 

- Try "staggered" saturation

- Simulation?

**Comment by diegogentilepassaro** [comment]
@gabrieleborg let's put this task on hold until we wrap up #24 , as per @santiagohermo comment we might be able to figure out the overlapping events issue there.

**Comment by gabrieleborg** [comment]
I agree, that's fine.

**Comment by santiagohermo** [comment]
@diegogentilepassaro @gabrieleborg 

I spent a couple of hours in this task trying to run an event study that allows for estimation using all events. For that, I rewrote the code that generates the estimating panels and now I generate dummies ``d_0, d_1, d_neg1, ..., d_`w', d_neg`w'`` and I define the off period dummy as
``d_off_event = 1 - max(d_0, d_1, d_neg, ..., d_`w', d_neg`w')``

As it turns out, this does not saturate the model. Why? For some periods the same more than one dummy are equal to one. Then, ``d_off_event_ == 1 - (d_0_i + d_1_i + d_neg1_i + ..)`` does not hold for all observations `i`, since in the period `i` where more than one dummy is one this will brake. 
We have to think how to saturate the models correctly.

---
I still produced some output which I briefly discuss below. The relevant folder is [`analysis/event_study_dummies`](https://github.com/diegogentilepassaro/min_wage_rent/tree/c261007b17421510f5de1473173bb9b6cc5730a5/analysis/event_study_dummies)
- To make sure my code works, I ran the same last event study as diego did in #24 (See files which name start with `last_`). For some variables the model happens to be fully saturated (you can see that the `d_neg1` is ommited. In those cases, the results are nearly identical. For example
   - medrentpricepsqft_mfr5plus_12: [old plot](https://github.com/diegogentilepassaro/min_wage_rent/blob/26f76e5e164faa39f19e34aa9540f8e9d10a0803/analysis/event_study/output/medrentpricepsqft_mfr5plus_last_sal_mw_event_rel_months12.png) vs [new plot](https://github.com/diegogentilepassaro/min_wage_rent/blob/c261007b17421510f5de1473173bb9b6cc5730a5/analysis/event_study_dummies/output/last_medrentpricepsqft_mfr5plus_12.png).
   - medlistingpricepsqft_sfcc_12: [old plot](https://github.com/diegogentilepassaro/min_wage_rent/blob/26f76e5e164faa39f19e34aa9540f8e9d10a0803/analysis/event_study/output/medlistingpricepsqft_sfcc_last_sal_mw_event_rel_months12.png) vs [new plot](https://github.com/diegogentilepassaro/min_wage_rent/blob/c261007b17421510f5de1473173bb9b6cc5730a5/analysis/event_study_dummies/output/last_medlistingpricepsqft_sfcc_12.png)
- Many event study with all events show a positive effect. However, they are not centered in 0 due to the saturation issue.
- Some event studies show a really big variance. I believe that in these cases the dummies are nearly collinear, and that makes the variance blow up. Example: [last_medlistingpricepsqft_sfcc_24](https://github.com/diegogentilepassaro/min_wage_rent/blob/c261007b17421510f5de1473173bb9b6cc5730a5/analysis/event_study_dummies/output/last_medlistingpricepsqft_sfcc_24.png)
- I also created the unused event little dynamic variables with 12 months window. I'm not using them (see [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/c261007b17421510f5de1473173bb9b6cc5730a5/analysis/event_study_dummies/code/all_event_study.do#L12-L13)) to increase comparison with the results in #24


Looking forward to talk about this and figure out a way to solve it!

**Comment by santiagohermo** [comment]
Next steps here: 
- Run the models omitting `d_neg1`. This entails creating a new function to plot the coefficients, as `coefplot` seems not to work for this.
- Control for dynamics around unused events rather than the cumulative sum (change [these](https://github.com/diegogentilepassaro/min_wage_rent/blob/c261007b17421510f5de1473173bb9b6cc5730a5/analysis/event_study_dummies/code/all_event_study.do#L12-L13) lines).
- Add a new estimation with only events that have non-overlapping windows. I visualize a new folder in analysis named `event_study_nonoverlap`

We could also study the code used in Cegniz, Dube et al [stored here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCTC7)

Feel free to jump in if you have bandwidth @gabrieleborg @diegogentilepassaro

**Comment by santiagohermo** [comment]
Update @gabrieleborg @diegogentilepassaro : I force the model to omit the `d_neg1` dummy even though the model is not saturated. [This is the output](https://github.com/diegogentilepassaro/min_wage_rent/tree/0e728bb9bf35310f3d0dcb64557977851f67826f/analysis/event_study_dummies/output).

Comments:
- The effect is there. However, not saturating is messing things up in many cases. Examples: 
   - In [all_medrentpricepsqft_sfcc_12.png](https://github.com/diegogentilepassaro/min_wage_rent/blob/0e728bb9bf35310f3d0dcb64557977851f67826f/analysis/event_study_dummies/output/all_medrentpricepsqft_sfcc_12.png) the pretrend is not centered at 0
   - In [all_medlistingprice_sfcc_24.png](https://raw.githubusercontent.com/diegogentilepassaro/min_wage_rent/0e728bb9bf35310f3d0dcb64557977851f67826f/analysis/event_study_dummies/output/all_medlistingprice_sfcc_24.png) excluding the -1 dummy does not change the remaining coefficients at all.
- The `last` event methodology plots look nearly identical to #24, which is reassuring.
- Controlling for a small dynamics around unused events (dummy for [-6,-1] and [0,6]) brakes the pretend coefficients in the `last` methodology. The `all` methodology nearly doesn't change. These makes sense because unused events in the `last` methodology only happen before, so they overlap with the pretrend.

I still owe you guys the non-overlapping. I'll try to do it this weekend. Talk to you tomorrow!

**Comment by santiagohermo** [comment]
I tried to build the data for the nonoverlapping methodology @diegogentilepassaro @gabrieleborg . I require for a non-overlapping event to have 2 windows free before and after, expect if the event is the first one (in which case I require one window _before_) or the last one (in which case  I require one window _after_). Unfortunately, this definition picks up no events in the rents dataset. Some are picked up in the listings.

This is what you guys have in mind?

Some summary statistics on num of events used in each specification:
|                     |  all_N   |  last_N  |  nonoverlap_N |
| ---                | :---:      | :---:     | :---:                   |
| listing w=12 | 8,644   | 3,083  | 531                   |
| listing w=24 | 6,755    | 3,072  | 194                   |
| rents  w=12 | 1,216    | 398     | 0                       |
| rents  w=24 | 892       | 395     | 0                       |

**Comment by santiagohermo** [comment]
Per call here I will:
- Check zipcodes with 1 event and understand why the non-overlapping methodology is not selecting those.
- Try the non-overlapping methodology in its current form with a small window and construct the table [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/25#issuecomment-622395122). This should select all events.
- Try the `all` specification with increasing off_window dummies.

**Comment by santiagohermo** [comment]
Summary statistics on num of events (times the `d_0` dummy is 1) used in each specification for several windows:

|  Event type   |  all_N   |  last_N |  nonoverlap_N |
| :---                | :---:      | :---:     | :---:                   |
| listing w=1 | 11,167   | 3,240  | 11,167               |
| listing w=6 |  10,301   |  3,172  |  1,360             |
| listing w=12 | 8,644   | 3,083  | 531                   |
| listing w=24 | 6,755    | 3,072  | 194                   |
| rents  w=1 | 1,566      | 404     | 1,566                |
| rents  w=6 |  1,469     |  404     |   145                |
| rents  w=12 | 1,216    | 398     | 0                       |
| rents  w=24 | 892       | 395     | 0                       |

_Note: I constructed this table manually by running `preclean_event_studies.do` for multiple windows._

The nonoverlap precleaning function seems to work in that setting w=1 picks the same events as the all specification. However, the number of selected events seems to decline very rapidly with `w`.

I will explore a bit why this is the case. It could be either 1) coding error, 2) there are very few zipcodes with only one event that may be picked up by the non-overlapping methodology with "high" `w`.

**Comment by santiagohermo** [comment]
Per call, we want to wrap up this issue. Before doing that, I will try out an "infinite dummies" approach, meaning that I will create dummies for all possible relative times wrt the event. This will saturate the model. We want to plot only the desired window dummies.

After doing that, I will 
- make a summary of the findings,
- send this task to PR, and 
- create a new task to discuss the ''stacked events'' design.

**Comment by santiagohermo** [comment]
Update @diegogentilepassaro @gabrieleborg. I implemented the infinite dummies above (I call it messy because I create many dummies that are later ignored. I also kept the 12 and 24 windows in preclean even though they are not strictly necessary). [This is the folder](https://github.com/diegogentilepassaro/min_wage_rent/tree/1eb470ddf108a523dadc421931df4abde84c7b8f/analysis/event_study_dummies).

Main takeway: The plots look much better.


Note that we are not 
<details>
  <summary>Click to expand!</summary>
  
| event_dummy | d_0 | d_1 | d_neg1 | d_2 | d_neg2 | d_3 | d_neg3 |
| ---------------  | ---  | ---  | ---         | ---  | ---        | ---   | ---        |
| 0                      | 0    |
| 0                      | 0    |
| 0                      | 0    |

</details>

**Comment by santiagohermo** [comment]
Per @diegogentilepassaro's comment, the model may be saturated due to the fixed effects. I will test this by running one specification with all dummy variables (instead of reghdfe) and testing whether STATA omits anything.

**Comment by gabrieleborg** [comment]
Great job @santiagohermo. 

I have one question: which control did you use? only the two-way FEs? Few comments here: 

- Focusing on the last event methodology, we see that the post-event dummies in the 24-months spec goes up to 4% increase. I don't remember if that's the case as well in the specification Diego implemented when producing `analysis/test_event_study/output/rent_12_the_FEs_limit.png` as there we have a 12 month windows, but we should check it.

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg ! In terms of the estimation, I run the same as Diego did in #24.
https://github.com/diegogentilepassaro/min_wage_rent/blob/559fd8ae75294970c7b8601797c9f3707e1ebe69/analysis/event_study_dummies/code/all_event_study.do#L81

I absorb `zipcode calendar_month year_month` and I add two possible controls for unused events:
https://github.com/diegogentilepassaro/min_wage_rent/blob/559fd8ae75294970c7b8601797c9f3707e1ebe69/analysis/event_study_dummies/code/all_event_study.do#L11-L13

Comparing with @diegogentilepassaro's results in #24, note that this `last` plots include dummies for all relative times, so they may be different. You are right, it does go to 4 percent and it seems to that it's still increasing up to period 35.

See coeffs below. (GitHub is not loading the [make.log](https://github.com/diegogentilepassaro/min_wage_rent/blob/1eb470ddf108a523dadc421931df4abde84c7b8f/analysis/event_study_dummies/output/make.log), so I took a screenshot)

<details>
  <summary> See some raw coeffs of last_medrentpricepsqft_sfcc_24 </summary>
 
![image](https://user-images.githubusercontent.com/45404755/81875486-5f796380-954e-11ea-8223-2a6da2697a40.png)

</details>

**Comment by santiagohermo** [comment]
Per call today, we will be closing this issue. The branch will be deleted and none of the code here will be implemented as of now. Thus, in order to prioritize other tasks, there will be no PR here.

The main deliverable here is some code that implements event studies with dummies. We may revisit this branch if we in the future decide this could be useful.

---
### Summary and Main Conclusions
- We tried an implementation with dummies around the event [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/25#issuecomment-622237451). The relevant folder is [this one](https://github.com/diegogentilepassaro/min_wage_rent/tree/0e728bb9bf35310f3d0dcb64557977851f67826f/analysis/event_study_dummies). We noted the difficulty of saturating the model.
- We implemented increasing off window dummies in commit https://github.com/diegogentilepassaro/min_wage_rent/commit/2324c1f74eccbdaadb64de9e749ac0f5f3e0474b. This did _not_ fix the saturation issue.
- In https://github.com/diegogentilepassaro/min_wage_rent/issues/25#issuecomment-623215411, we noted that the non-overlapping methodology was inapplicable with 12 window dummies because it throws away too much data (it requires 24 months clean to either side of the event, what is relatively uncommon).
- As a last attempt to fix the saturation we tried "infinite dummies" in https://github.com/diegogentilepassaro/min_wage_rent/issues/25#issuecomment-627970744. The relevant folder is [this one](https://github.com/diegogentilepassaro/min_wage_rent/tree/1eb470ddf108a523dadc421931df4abde84c7b8f/analysis/event_study_dummies). This seemed to work and the plots look center, however the econometric properties are not clear. We could revisit this implementation later.

**Comment by santiagohermo** [comment]
I will use this issue to bring to master the code for the "dummies" specifications. I will update the respective branch from master and prettify the existing code.

**Comment by santiagohermo** [comment]
Thread continues in PR #34
