### ISSUE TITLE
Revise discussion section

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#273]
Looks like our read of the elasticity of rents to the MW from Yamagishi is wrong @diegogentilepassaro @gabrieleborg!

In this issue we want to revise the "Discussion" section, correct our quoting of Yamagishi, and make sure that other numbers we quote are right. Can you help with this @diegogentilepassaro @gabrieleborg?

After that we'll have a correct draft online, and later we can decide what are the next steps.

**Comment by diegogentilepassaro** [comment]
@santiagohermo the elasticity in [Yamagishi](https://www.sciencedirect.com/science/article/abs/pii/S0166046221000090) is 0.25-045. This is an order of magnitude larger than ours, so we should probably change the discussion section and try to explain why ours is more reasonable. Perhaps, bringing to the paper the effects that we find on the wage bill and on employment is a way to do that.  I see 2 alternative paths:
- Compute effects on wage bill and employment and tie everything together. Even if estimation is not amazing, hopefully it aligns with the literature and helps interpret everything so that Yamagishi's numbers are proven unreasonable because it needs huge swings in employment and wage bill to be true. Probably mention the fact that elasticity of supermarkets is also low as in our case.
- Just reference the literature on wage bill and employment, and the one of supermarkets.

Maybe an alternative exercise, could be to understand the effect of changes in income on rents more generally. In that case, we could use the effect of MW as an instrument for a regression of rents on wage bill. That seems like a different paper, but maybe an exercise like this in the appendix is cool since it hopefully shows that changes in income have a small effect on rents. 

Should we meet at some point to define how to change the draft as per this problem @gabrieleborg @santiagohermo ?

**Comment by gabrieleborg** [comment]
Hey guys!

I agree to first fix the quotes, and then meet to discuss next steps. I can meet starting the Oct 8th week.

**Comment by diegogentilepassaro** [comment]
@santiagohermo and @gabrieleborg, I updated the discussion section. I think there is a lot to change in the introduction too, and I would structure the paper differently for the next iteration, but those are all things to discuss in a couple of weeks. Let me know your thoughts on the changes now. Also, what do you think if we meet on Tuesday, October 10th? Let's settle on a time that day or that week. 

@gabrieleborg, could you double-check that the other elasticities that we reference in the discussion section (and elsewhere) are correct?

**Comment by santiagohermo** [comment]
Gracias @diegogentilepassaro! I looked at your edits and I had a couple of suggestions to restructure [that paragrpah](https://github.com/diegogentilepassaro/min_wage_rent/blob/172be83e0148a3a93d9fb638bc6a43e546e84a29/paper_slides/paper/results.tex#L382-L429):

1. Start saying that our estimates are in the lower end of the few existing estimated elasticities of the MW on rents.
2. Say that our results are similar to Hughes, who focuses on low-income households in the US. (Make sure that this number is right)
3. Then say that our results are smaller than both Yamagishi2021 and AgarwalEtAl2022 (instead of saying it in different places, to shorten and be less repetitive). Something like "our estimates are an order of magnitude smaller than Yamagishi2012 and AgarwalEtAl2022, who find elastiticities of rents to the MW of XX and YY, respectively." 
4. Say that our focus is on local labor markets within cities, and in rents per square foot, so the setting is a bit different. However, in light of the literature of effects of the MW on income and consumption prices, we see our estimates as more plausible. Instead of [that example](https://github.com/diegogentilepassaro/min_wage_rent/commit/172be83e0148a3a93d9fb638bc6a43e546e84a29#diff-d94a2d03ac27bba815f79d440c82d99272dd20313ff1d69213134098c99727cdR390-R396) we can use [the computations we did before](https://github.com/diegogentilepassaro/min_wage_rent/blob/172be83e0148a3a93d9fb638bc6a43e546e84a29/paper_slides/paper/results.tex#L376-L380) and make a comparison like this. Assuming constant housing share, housing expenditure following a MW increase goes up by $s\beta$ and total income by $\varepsilon$. If $\beta > \varepsilon/s$ then real income would decrease following a MW increase. Assuming $\varepsilon = .1$ and $s=1/3$, then elasticities of rents to the MW larger than  $.3$ would lower real wages. We see this as an implausible outcome.
5. Try to keep the paragraph shorter.
6. Do we mention the comparison in the intro? If so, then we may want to review that.

I'm happy to review in a PR once this is done, and update the public version of the paper.

And yes, we want to double check that the elasticities we cite are correct. @gabrieleborg's help would be valuable.

**Comment by diegogentilepassaro** [comment]
Hola @santiagohermo! Thanks for the comments:
1. Agree!
2. Agree, @gabrieleborg could you please check if that one is right?
3. Also agree!
4. Agree with saying that our focus is on local labor markets within cities, and in rents per square foot, so the setting is a bit different and that in light of the literature on the effects of the MW on income and consumption prices, we see our estimates as more plausible. However, about the example, it should be in simple English without making reference to any parameter as that is much harder to follow and precludes people from reading the discussion without reading the other sections. If you want to choose an example that lines up with the one you pointed out that there then that works. The example should be straightforward and numeric, not a general statement.
5. Probably by implementing 1. and 3. this will happen.
6. We don't but the point is that we should. I thought the discussion on [Yamagishi's intro](https://www.sciencedirect.com/science/article/pii/S0166046221000090) was pretty good in that respect.

Will take another stab when ever I have some down time!

**Comment by gabrieleborg** [comment]
Hey @diegogentilepassaro @santiagohermo ! I am (almost) back - I am flying back to NYC tonight.I Will review this during the week and check the estimates citations are correct.

**Comment by gabrieleborg** [comment]
Hey folks, I'm back! 

2. I reviewed Hughes paper. I confirm his estimates are similar to ours (0.0543). One thing I'd correct in the [summary and discussion section](https://github.com/diegogentilepassaro/min_wage_rent/blob/172be83e0148a3a93d9fb638bc6a43e546e84a29/paper_slides/paper/results.tex#L412) is the fact that we mention how he uses cross-sectional data, while he actually uses a repeated cross-sectional data set. I think mentioning it will make the comparison a bit more robust. 

I also double-checked the Yamagishi estimate, and I confirm it's 0.25-0.45.  In general, I think the all comparison with Yamagishi has taken a bit too much emphasis (not for our fault!). The more I think about it, the more difficult it seems to me to make a precise comparison between our and his study: 
    1. the study is at a different aggregation level. Japan's prefectures (or US counties) are way bigger than to zip-codes, and I don't think there's a clear and evident reason for why the results aren't compatible. The results with US counties aren't "that" different even, while those for Japan come from a completely different environment. Different labour market, different labor force composition, different housing market, etc. 
    2. Yamagishi's estimates for Japan focuses on low-quality apartments. Our study does not, so we're even studying a different type of housing. This to me makes it even more difficult to draw any meaningful comparison between the two - at least when it comes to the magnitude of the effect. 
    3. Yamagishi explicitly says that "Although some units are aimed at families,Japanese rental markets are mainly for singles and couples because non-poor families with children typically own a house or an apartment unit." Our main outcome variable is the median rent for Single family houses, condos and CC. Given the prevalence of single famlly houses in the US, this to me suggests how the family composition of the houses analyzed can be pretty different, making it even more difficult to compare the results. 
    4. Yamagishi estimates his model directly using listing-level data, while we use the median of the zip code. If the minimum wage effect has an impact on the distribution of rents, then we may have the average effect being different (and larger) than the effect on the median.  
    
   So in general, I agree on keeping the comparison with that paper rather short, and I agree with @diegogentilepassaro in avoiding too many details in our discussion, because it otherwise looks like we're trying too hard to justify a difference that has many reason to exists.

**Comment by santiagohermo** [comment]
Great review @gabrieleborg! Thanks for the help @diegogentilepassaro @gabrieleborg.

In dc7f299c I implemented some fixes directly in `master`, my bad haha.

I will update the draft in arxiv with this fix, and hopefully we'll discuss next steps soon.

Let me know if you have any thoughts, if not I'll close this issue and the other branch.

**Comment by santiagohermo** [comment]
Completed.
