### ISSUE TITLE
Draft - June 2020

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#37]
**Goal**
Produce an early-stage draft to circulate mostly internally to faculty. 

**Steps**

1.  Link overleaf to repo

2. Review and complement the following sections: 
    - Research question
    - Methodological Framework (broad)
    - First set of results: classic event-study using last event. 
    - Limitation of classic framework
    - first difference framework

**Comment by gabrieleborg** [comment]
Step 1 is completed. See README.md  in [`draft_june2020/`](https://github.com/diegogentilepassaro/min_wage_rent/tree/master/draft_june20) for instructions on how to use.

**Comment by gabrieleborg** [comment]
@diegogentilepassaro good mornning! 

I have started working on the draft, so far so good! I am discussing the initial results now, and then I will continue by highlighting the limitation of such design and introducing the first diff specification.  there are a couple of issues though on which I need your feedback (please look in the [draft](https://github.com/diegogentilepassaro/min_wage_rent/tree/master/draft_june20) to check these): 

1.  In the empirical strategy section, we introduce the main specification that has zipcode and countyXyearmonth FE as baseline controls (plus additional controls in X). You have also commented the importance of those in the result section (p.9). However, when I checked the specification we actually use in [`analysis/event_study/code/last_event_study.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/master/analysis/event_study/code/last_event_study.do) what we are actually using is: **zipcode FE**, **stateXyearmonth FE**, **countyXcalendarmonth FE**, and control for unused event.  Is this the updated version? Shall I comment based on this one by changing the description of our baseline, or shall I actually re-run the specification with **countyXyearmonth** and update the figure? By looking at [this event study test](https://raw.githubusercontent.com/diegogentilepassaro/min_wage_rent/master/analysis/test_event_study/output/rent_6_the_FEs_limit.png) it actually doesn't look like the spec with **countyXyearmonth** works though.

**Comment by santiagohermo** [comment]
Note: We need to run `derived` properly to make sure the version of `derived_large` in the google drive gets the changes merge from #35 (specifically, the trend vars)

**Comment by gabrieleborg** [comment]
@diegogentilepassaro  @santiagohermo  Hey guys, 

I started working on some motivation plots [here](analysis/descriptive/code/wage_rent_motivation.do). I couldn't finish but I was initially using the [county_quarter_panel_all.dta](derived/county_quarter/output/data_file_manifest.log) as it has wages, mw and rents and prices. For the moment I was tryng to build the following figure (but it still not coming out as expected): 

1. for every county, meaure the number of MW changes they had in a given period (e..g 2010, 2019) and group them in above and below median number of  MW changes

2. take the yearly average of rent and price

3. create a yearly average for the two groups (above and below median) and plot the time evolution. 

Ideally I wanted to show that in counties with more MW changes rents went up more, but it's not so neat and there's a bis spike in one of the series. 

Also, I started with the county level panel because I wanted to use wages at the beginning, but I think if we use Mw changes only we can go back to zipcode which is more relevant. 

Finally, I don't know why it doesn't save the output in the output folder when I run it with python...I will check this tonight.

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg. That plot you describe sounds really cool, hope it works!

Another interesting would be to simply correlate some characteristic from the census with average rents in some year (or all years) at the zipcode level, maybe household income. I don't know if this is the case, but if the census has a rent variable we could also use that one. If the correlation is positive, this would suggest that the minimum wage has room for changing rents by altering the lower tail of the distribution of wages.

**Comment by gabrieleborg** [comment]
Hey @diegogentilepassaro  @santiagohermo ! 

I finished creating some simple motivation figures. Some went in the direction we were expecting, some not really. You can find all figures created in [`analysis/descriptive/output/`](https://github.com/diegogentilepassaro/min_wage_rent/tree/Issue37-Draft-June-2020/analysis/descriptive/output) while you can see the script lives in [`analysis/descriptive/code/wage_rent_motivation.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/Issue37-Draft-June-2020/analysis/descriptive/code/wage_rent_motivation.do).  Note that I am using the `baseline_rent_panel ` and the `baseline_listing_panel`, so I am actually focusing on the zipcode we are using in the analysis. 

First I plotted the correlation, at the zipcode level, between outcomes (e.g. med rent sfcc) and the percentage change in the previous year. Note that I additionally control for year FE, population (2010), urban share (2010), median income (2010 ACS), share of blacks (2010) and number of housing units in the zipcode (2010). The correlations are generally positive. I think we could use some of them to say something like "in general, even after controlling for basic demographics, we do see a positive correlation between rent (and prices) and the change in MW". Here are a couple of outcomes we could use : 

#### medrentprcepsqft sfcc
![binsc_medrentpricepsqft_sfcc_pctMWch](https://user-images.githubusercontent.com/30894427/85206397-e826b480-b2ef-11ea-9d35-8d58525a3804.png)

#### medrentprcepsqft 2br
![binsc_medrentpricepsqft_2br_pctMWch](https://user-images.githubusercontent.com/30894427/85206424-13a99f00-b2f0-11ea-9686-8e9f2e180603.png)


#### medlistingpricepsqft sfcc
![binsc_medlistingpricepsqft_sfcc_pctMWch](https://user-images.githubusercontent.com/30894427/85206431-21f7bb00-b2f0-11ea-99ae-f201578123f7.png)

I then looked into the relationship between rents and demographics directly. Here results are a bit counterintuitive so I don't know whether to include them. Maybe it's worth to get a look at a particular example (e.g. Manhattan). In general, what I did was: 1) for each zipcode measure the percentage change in outcomes (e.g. rents) over a period of time; 2) for different demographics, create groups of zipcode based on the demo's quartiles; 3) plot the average percentage change in the outcome by the demo's groups. Here an example: 

![Dmedrentpricepsqft_sfcc_college_share20105](https://user-images.githubusercontent.com/30894427/85206559-08a33e80-b2f1-11ea-8d8d-6e5d09f087b6.png)

Obvisouly you can see how rents in more educated zipcodes went up more than in low-educated one, but this is no surprise as education heavily correlates with urban areas and gentrification process. Indeed: 

![Dmedrentpricepsqft_sfcc_med_hhinc20105](https://user-images.githubusercontent.com/30894427/85206542-ed383380-b2f0-11ea-918c-c38c0ee2b17a.png)

A couple of plots that are a bit more interesting perhaps are the one for black share and poor share (defined as the share of people living below the poverty line): 

![Dmedrentpricepsqft_sfcc_black_share2010](https://user-images.githubusercontent.com/30894427/85206591-2e304800-b2f1-11ea-91f2-3d49151b8e43.png)

![Dmedrentpricepsqft_sfcc_poor_share20105](https://user-images.githubusercontent.com/30894427/85206593-31c3cf00-b2f1-11ea-9d2c-d9c62598f820.png)

While you can see how changes in rents for zipcodes with more blacks was way smaller, interestingly the change was kind of similar once you group zipcodes based on the share of poor people. 

Let me know what you guys think and what we should add. I think we could go with two binscatter (one for rent and one for prices) and maybe the last one with groups based on poor share.

**Comment by diegogentilepassaro** [comment]
Thanks for this plots @gabrieleborg!

I agree with you that adding the rent and listing binscatters to the draft would be nice. As for the rest, the plots are very interesting. The puzzle is how is it possible that rent grows more in richer areas but less in areas with more African americans right?

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! That's a very interesting exploration. Beyond [the puzzle](https://github.com/diegogentilepassaro/min_wage_rent/issues/37#issuecomment-647046145) described by @diegogentilepassaro, I also found very interesting the quadratic relationship between the increase in the MW and rents. That's a pattern I was not expecting at all!

I was experiencing with event studies, based in the awesome work you guys did before. I will make a comment below describing what I found and how I plan to write the results.

**Comment by santiagohermo** [comment]
So, I've been working on the event studies part of the draft. As I kind of finished with a first pass on the theory, I started to modify the plots we produced to fit "the story" that we tell in the theory part of the draft. Here is a summary of what the story is (in my head) and what the plots actually look like. Curious to hear your thoughts here!

### Theory
This is more or less written down in the overleaf (I have to fix a few things after today's exploration). It goes like this:

1. We want to run something like equation {eq:ideal-event-study}, using all events. 

2. We can't run it for now due to several technical complications, which we discuss. We'll work on them in the future.

3. Then, we select only the last event to run a traditional TWFE event study. In our main specification we control only for unused events and we use units that are treated only (in a robustness we add county-specific parametric trends to this). This has under-identification issues, which we discuss.

4. We apply two solutions to deal with under-identification:
   - Drop zipcode FE and use county FE instead.
   - Keep zipcode FE and add untreated zipcodes.

### Results
I use rent psqft sfcc here, We have results for other categories that we can add as robustness.

1. The basic plot with zipcode and time FE using only treated units is [this one](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study_exploration/output/last_rentpsqft_sfcc_zfe_w6.png) (See [full regression output](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study_exploration/output/make.log#L530-L569), it only uses 46,000 observations). [Here](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study_exploration/output/last_rentpsqft_sfcc_zfe_w6_county-trend.png) with county linear and sq trend. It seems that no effect, but it has under-identification problems.

2. Solution 1: use county FE instead of zipcode FE. [This](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study_exploration/output/last_rentpsqft_sfcc_cfe_w6.png) is the plot and [here](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study_exploration/output/last_rentpsqft_sfcc_cfe_w6_county-trend.png) I add county trends. Still looks like nothing.

3. Solution 2 (_the good one!_): keep zipcode FE but add untreated units 
   - Here I added a [new function](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/lib/stata/min_wage/ado/create_event_plot_with_untreated.ado) to run the regression and to create the event plot. I think our previous implementation was off because it allowed a different constant to untreated units, which the regression {eq:last-event-study-control} does not.
   - [This](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study/output/last_rentpsqft_sfcc_w6.png) is the best event study (in my opinion), with [this full output](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study/output/make.log#L762-L802). It uses ~113,000 observations and t-values reach 3!
   - The above specification may be biased due to places with better economic conditions adding a minimum wage. Thus, add county trends as controls. [This](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study/output/last_rentpsqft_sfccw6_county-trend.png) is the result ([full output](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study/output/make.log#L983-L1033)). There still seems to be an effect, but standard errors are big and confidence intervals often cross 0.
    - `analysis/event_study` runs this specification (zipcode year_month FE + untreated units) to all our variables. See the [output](https://github.com/diegogentilepassaro/min_wage_rent/tree/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study/output). I think it works well with rents psqft.

4. Event size robustness. I think this is quite cool
    - use 0.75 cutoff to select events:
        - [zip & time FE + treated units only](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_size_robustness/output/last_rentpsqft_sfcc_event075_w6_treated-only.png)
        - [zip & time FE + all units](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_size_robustness/output/last_rentpsqft_sfcc_event075_w6.png)
        - [zip & time FE + all units + county_trend](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_size_robustness/output/last_rentpsqft_sfcc_event075_w6_county-trend.png)
    - use 0.25 cutoff to select events:
        - [zip & time FE + treated units only](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_size_robustness/output/last_rentpsqft_sfcc_event025_w6_treated-only.png)
        - [zip & time FE + all units](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_size_robustness/output/last_rentpsqft_sfcc_event025_w6.png)
        - [zip & time FE + all units + county_trend](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_size_robustness/output/last_rentpsqft_sfcc_event025_w6_county-trend.png)
   - I think the plots confirm that using all units is the way to go. Also, it suggests to me that events with larger increases have a higher impact.

My conclusion is that there is an effect. However, sometimes it is masked first by the under-identification issue and lack of power (both of which are problems with the base TWFE with treated units only specification). I think that having more events should help a lot (to increase power), and that using the untreated units is key. I will try to transmit this when I write the results in the upcoming days!

One cool thing is that untreated units are about 60,000, against about 45,000 treated. Borusyak and Jaravel say that if you have too few untreated units then the problem remains, which is not the case for us  (I think).

### Other ideas

I thought that running the event study specifications on the log of the rent variable would help to connect these results to the first differences, and hopefully bring back the bootstrap passthrough table (which was quite nice). However, there doesn't seem to be an effect. [This](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study/output/last_ln_rentpsqft_sfccw6.png) is the plot using the log of sfcc psqft, ZE & time FE + all units.

### Code

I changed the analysis folders `event_study`, `event_size_robustness` and `event_study_exploration`. I also created a [new function](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/lib/stata/min_wage/ado/create_event_plot_with_untreated.ado) to compute the event study plot using all units. **I think this function could use some reviewing** to make sure I didn't screw up. The other changes are relatively straightforward, so a full review could wait.

----

One last thing. The `event_study_exploration` didn't run correctly last time ([one do file broke :(](https://github.com/diegogentilepassaro/min_wage_rent/blob/9992f2827637c97989f214bc5c82fa57c25183f9/analysis/event_study_exploration/output/make.log#L1092-L1100) ), so I'm waiting for it to run fully and thus will update it very soon.

**Comment by gabrieleborg** [comment]
Hey guys! @santiagohermo @diegogentilepassaro 

Thanks @santiagohermo  for the overview, I think it looks great to me! I agree with the different steps of the story, even though I don't understand exactly why you changed the first spec we show to simply showing TWFE and controlling for county trend. We know it's underidentified, but once we were controlling for county-level seasonality  (e.g. county FE X calendar month) and the results we're looking better. Is it because adding county FE X cal. month worsen the underidentification issue? In that case ok, but if not I think we could keep that in your point 1, after the simple TWFE (maybe jointly with county trends).  

Also, shall I just add a bit of motivation with the correlation plot in the introduction section, or somewhere else? on one hand I think it's cool to show that already  at the beginning as we are saying why we're interested in studying that, but also the plots are based on `baseline_rent/listing_panel.do` files and so we would introduce them before explaining what we do with the data. Where do you think I shall add them?

**Comment by santiagohermo** [comment]
In https://github.com/diegogentilepassaro/min_wage_rent/commit/c0f436bbcd691e77ffe1224745e2ff1bdbef694e I updated master with the current status of the branch

**Comment by santiagohermo** [comment]
I updated master from the current branch in https://github.com/diegogentilepassaro/min_wage_rent/commit/338e252ed722087af444c79601e72d8835fed3da. The goal is to bring the county level results to the overleaf

**Comment by gabrieleborg** [comment]
@diegogentilepassaro @santiagohermo Hello Guys!

Before starting the new tasks I fixed the very last things on the draft. Specifically: 

1. I fixed the sum stats table. I honestly don't know what was wrong before. I simply re-run the code and now the table makes sense: 
<img width="755" alt="Screen Shot 2020-09-04 at 12 16 50 PM" src="https://user-images.githubusercontent.com/30894427/92262054-89151c80-eea8-11ea-8295-4ce211ccd126.png">

As you can see, in our final rent baseline panel we have 16 percent of the US population. This is a bit low, but I think it's also due to the fact that we're keeping only balanced zipcodes. 

2. I finished adding notes to tables and figures. 

I mistakenly worked on master. Thankfully I didn't change much, I only revised a couple of very  minor errors. I think that therefore now we could close this issue and merge the branch, right? 

Also, I am still trying to connect Overleaf to GitHub on my new laptop, so you can find the updated draft version on Overleaf.

**Comment by gabrieleborg** [comment]
quick update: I fixed median income as well.

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! 

For the record, this is the last version of the pdf: [The_Impact_of_MW_on_Rents_and_House_Prices___2020_06.pdf](https://github.com/diegogentilepassaro/min_wage_rent/files/5189509/The_Impact_of_MW_on_Rents_and_House_Prices___2020_06.pdf)

**Comment by santiagohermo** [comment]
[This release](https://github.com/diegogentilepassaro/min_wage_rent/releases/tag/Summer2020) stores the current version of master and the pdf of the draft. 

We will move on from the intial draft and get into implementing new improvements in the data and research design. See #39
