### ISSUE TITLE
Repo maintenance

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#41]
After the summer we are starting to work again on this project. This task is a part of that process, in which we will:

- Drop things we won't be using in the future (event studies?)
- Improve code or organization of files if needed
- Set up [gslab_make with python 3](https://github.com/gslab-econ/gslab_make) (santi)

I will focus on this task this week, requesting your input when needed @gabrieleborg @diegogentilepassaro

**Comment by santiagohermo** [comment]
Question @diegogentilepassaro @gabrieleborg. Do we want to keep the county-quarter analysis, or should I delete it?

**Comment by gabrieleborg** [comment]
@santiagohermo mmm I think we could keep it for the moment, and delete it maybe later? I am saying this because I will have to send a draft soon to Matt and Emily, and if they ask us to substantiate a bit more why our analysis is superior to previous papers, we can readily put a couple of plot in Appendix.

**Comment by santiagohermo** [comment]
Sounds good @gabrieleborg, thanks for the quick reply!

**Comment by diegogentilepassaro** [comment]
I agree with keeping it too! We can probably improve the hay we’ve done at a later stage by adding directly Zillow data at the county-month and stress the importance of having small areas.

**Comment by santiagohermo** [comment]
I updated `derived/zipcode_month` , but the data file manifest is showing that I added a lot of unintended variables (see [this diff](https://github.com/diegogentilepassaro/min_wage_rent/commit/04e4fb301e65ec0399762d0d2d8e7e225c3eeb33#diff-e7cccde3eb0401ed89f65ec7cd341bad)). I almost didn't change the code though, so I'm not sure why. Any thoughts on why this might be, @gabrieleborg?

**Comment by santiagohermo** [comment]
Another question: I'm getting to updating `analysis`. It seems to me that we are creating `preclean`s dataset a lot there. What do you say if we add one folder (`analysis/estimating_panel` or something) to make the preclean only once, @diegogentilepassaro @gabrieleborg?

**Comment by santiagohermo** [comment]
Per call, I'll wrap up this issue once we are working on the draft (to avoid conflict with existing branches)

**Comment by gabrieleborg** [comment]
> I updated `derived/zipcode_month` , but the data file manifest is showing that I added a lot of unintended variables (see [this diff](https://github.com/diegogentilepassaro/min_wage_rent/commit/04e4fb301e65ec0399762d0d2d8e7e225c3eeb33#diff-e7cccde3eb0401ed89f65ec7cd341bad)). I almost didn't change the code though, so I'm not sure why. Any thoughts on why this might be, @gabrieleborg?

That's very weird. If you look at [`base/demographic/output/data_file_manifest.log`](https://github.com/diegogentilepassaro/min_wage_rent/blob/issue41-repo_maintenance/base/demographics/output/data_file_manifest.log) you can see that the baseline zip_demo.csv file is outputted wrong. I tried re-run `base/demographics` from master right now and it comes out ok....so you may want to look at what's going on then I think, because in `derived/zipcode_month` it looks like it merged this "wrong" `zip_demo.csv` file

**Comment by gabrieleborg** [comment]
> Another question: I'll be updating `analysis` soon. It seems to me that we are creating `preclean`s dataset a lot there. What do you say if we add one folder (`analysis/estimating_panel` or something like that) to make the preclean only once, @diegogentilepassaro @gabrieleborg? The good thing is that we will be applying all the sample restrictions that we are interested in only one time.

As you mentioned in your other comment, let's wait to PR the issues we are working on right now and let's re-assess what's best to do for this.

**Comment by santiagohermo** [comment]
Not enough time to work on this at the moment.
