### ISSUE TITLE
Benchmark zillow rents with other rent sources

### ISSUE THREAD

**Issue by santiagohermo** [diegogentilepassaro/min_wage_rent#47]
[GOAL]
Per meeting today, we want to add some benchmarking of our rent variables

[STEPS]

1. Collect and organize alternative data sources. Some of these has already been done in `base/alt_rents/`. Consider using the FMR, the Case-Shiller index and Zillow aggregated at different geographic units

2. Construct a time series figure that shows the time path of our rents variable compared with alternative sources

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro

In the first commit I started working with the Small Area Fair Market Rent, and I compare that to our zillow rent data. This data comes at the zipcode-year level. I first researched a bit into how they are calculated. From what I understood, there are 2 methods in use (see page 41641 of the [Federal Register/Vol. 82, No. 169](https://www.huduser.gov/portal/datasets/fmr/fmr2018/FY2018-FMR-Preamble.pdf)):  

- Before 2018: product of the FMR ratio (computed at the MSA level) and a ziplevel rent ratio. The latter is obtained by dividing the zipcode-level gross rent for **all bedroom** houses by the MSA-level gross rent for all bedroom houses. 

- Starting in 2018: 
   - for zipcode with enough data (i.e. estimated with margin of error ration below .5 and more than 100 obs): 40th percentile of the gross rent distribution (there's a sub procedure related to each house type, i.e. 0br, 1br, .., 4br) 
   - for zipcode with not enough data: see Before 2018 procedure. 

One thing to notice however is that the rent estimates are actually averaged over 3 years. Despite that, I [created `analysis/zillow_benchmark`](https://github.com/diegogentilepassaro/min_wage_rent/tree/%2347-zillow-rent-benchmark/analysis/zillow_benchmark), where I added [`analysis/zillow_benchmark/code/compare_zillow_zipcode.do`](https://github.com/diegogentilepassaro/min_wage_rent/blob/%2347-zillow-rent-benchmark/analysis/zillow_benchmark/code/compare_zillow_zipcode.do). Here I adopt the following procedure: 

1. I remove from `drive/derived_large/zipcode_yearmonth_panel_all.dta` all zipcodes with missing data on the 3 most populous series we have: 2br, sfcc (our main one), and mfr5plus. 

2. I then create 2 different version of zipcode level annual series: one taking the year average; and another one selecting a specific month (e.g. 6, or 12). 

3. I then merge the two zipcode-year datasets, and compute the yearly averages to plot (I translate every amount in 2012 USD for visual clarity, but nothing changes much). 

In the following pictures notice that I intentionally left them "raw", so that we can fully discuss what's best for us. Namely, even though in the end our sfcc series is the only one that shows a reasonable pattern, I wanted to show you how 2br and mfr5plus have instead a very weird evolution. This to me signals a strong composition bias and so it's no surprise we don't get any real result when we run first difference models on those. 

_yearly averages_
<img width="1188" alt="Screen Shot 2020-09-29 at 2 38 03 PM" src="https://user-images.githubusercontent.com/30894427/94601382-697fd280-0261-11eb-89bb-b93a23620fc9.png">

_June rent_
<img width="1185" alt="Screen Shot 2020-09-29 at 2 39 14 PM" src="https://user-images.githubusercontent.com/30894427/94601510-9633ea00-0261-11eb-8b9e-3319efb0c354.png">

_December rent_
<img width="1185" alt="Screen Shot 2020-09-29 at 2 40 02 PM" src="https://user-images.githubusercontent.com/30894427/94601577-acda4100-0261-11eb-8178-f8e0a9deb40a.png">

As you can see, our sfcc series is higher than the safmr 4br one. Given the fact that however safmr are computed mostly based on the 40th percentile of gross rent distribution, this is not surprising. what I think is good is that it shows the same behavior. Additionally, the category single family / condo actually include a combination of 1, 2, 3, 4 and more bedroom houses. One possible extension could be to use the yearly Survey of Construction to build weights for the different house sizes according so to match that year single family house composition (e.g. 30 % 2br, 10% 1br, etc). 

Alternatively, I plotted the zipcode level correlation between sfcc and the different sfamrs (absorbing year FE): 
<img width="907" alt="Screen Shot 2020-09-29 at 4 28 48 PM" src="https://user-images.githubusercontent.com/30894427/94612276-dea6d400-0270-11eb-90b9-48d5919be4fb.png">

Here we can see how there's a pretty strong correlation, and how indeed sfcc can be thought of as a combination of different types of houses: 1- and 2- br safmr appear to be slightly above  a 45 degree line, while 3- and 4- slightly below. 


Lastly, I spent some time looking for alternative data source. Unfortunately I didn't have much luck. The Case-
Shiller indexes available refer to house prices, not rent, and so it is not very informative in relation to our data. I then looked at the [FRED consumer price index for rent on the primary residence in U.S. cities](https://fred.stlouisfed.org/categories/32416?t=rent&ob=pv&od=desc), but it looks like this comes at the national level. In addition to that, it is an index so i am not sure how informative could be when compared to our series. But I would like to hear your take on that.

**Comment by diegogentilepassaro** [comment]
Thanks @gabrieleborg! This first pass comparing with the SAFMR looks really great and despite the fact that we are comparing a median with a 40th percentile measure that differs on the number of rooms it is really reasonable. Moreover, the time series variation exhibited by the Zillow SFCC median variable is essentially the same as the one for the SAMFR and that seems what we should care about. Could you please compute the time-series correlation between Zillow's SFCC and any SAFMR series? 

As for the last plot: What exactly do you mean by zipcode level correlation? is it at a particular moment in time?

**Comment by gabrieleborg** [comment]
Probably I wasn't clear enough @diegogentilepassaro , but the last plot is the time-series correlation! I computed that for zillow SFCC and 1, 2, 3 and 4 br SAFMR series (in each I control for year FE). Shall we add the rho for each correlation?

**Comment by diegogentilepassaro** [comment]
Thread continues in #52!
