### ISSUE TITLE
Add LODES data 

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#51]
**Goal**
Add LODES data to compute the approximate number of low-income workers living and working in each zipcode pair. 

**Steps**
Download data from [here](https://lehd.ces.census.gov/data/)

**Comment by santiagohermo** [comment]
This is a case similar to QCEW @gabrieleborg. The data is organized in endless folders and files, and it's _really_ heavy (At one run I left it for ~15 minutes and it didn't even passed 10 states for the first year! ). To download it, I created a code based on [this one](https://github.com/UrbanInstitute/lodes-data-downloads/).

The data goes from 2002 to 2017. The data is coded at the census block level (see [here](https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.0.pdf)). There are three categories of LODES data:

- OD – Origin-Destination data, jobs totals are associated with both a home Census Block and a
work Census Block
- RAC – Residence Area Characteristic data, jobs are totaled by home Census Block
- WAC – Workplace Area Characteristic data, jobs are totaled by work Census Block

To save time (and because we don't need anything else), I'm downloading it from 2009 to 2017. I'm downloading the three types at this moment, but we can easily change that and speed up the process significantly.

Any thoughts?

**Comment by gabrieleborg** [comment]
Thanks @santiagohermo ! 

Actually I was thinking about using it as time-invariant characteristics (John says that when it comes to these type of demographics, what's important is the cross sectional distribution and that the time variation in comparison is minimal). Maybe we can only limit ourselves to, say, 2017 and 2015 (mid year)?

**Comment by santiagohermo** [comment]
That sounds great @gabrieleborg! I will limit to those years. It looks like I got an error for too many url requests (I was trying to fix a bug :/). I will set it up running again later.

**Comment by diegogentilepassaro** [comment]
I agree that the time-invariant characteristic should be the most important for heterogeneity analysis. However, just checking, maybe we can use some of these variables as additional controls?

**Comment by santiagohermo** [comment]
Continues in #53
