### ISSUE TITLE
Add Recent Minimum Wage Data

### ISSUE THREAD

**Issue by gabrieleborg** [diegogentilepassaro/min_wage_rent#7]
**Goals**
Add both state and local (county and city) level minimum wage data for the period Aug 2016 - Dec 2019. 

**Sources**
- State-level changes: [link](https://www.ncsl.org/research/labor-and-employment/state-minimum-wage-chart.aspx)
- Local-level changes: [link](http://laborcenter.berkeley.edu/minimum-wage-living-wage-resources/inventory-of-us-city-and-county-minimum-wage-ordinances/)

**Steps**
1. Add state changes to a state-level xslx file with the following columns (leave empty if not applicable): statefips, statename, year, month, day, VZ_mw, VZ_mw_healthinsurance, VZ_mw_smallbusiness
2. Add local changes to a local-level xlsx file with the following columns (leave empty if not applicable): statefips, statename, locality, year, month, day, VZ_mw, VZ_mw_tipped, VZ_mw_healthinsurance, VZ_mw_smallbusiness, VZ_mw_smallbusiness_mincompensation, VZ_mw_hotel
3. Adjust the dofiles in base to build the state and substate panel of minimum wage changes

**Comment by santiagohermo** [comment]
Per call today I will collaborate with this task. After this and #13 are done we will move on to new tasks.

**Comment by santiagohermo** [comment]
Interestingly, MW changes by counties in Iowa are not enforceable since March 30, 2017. This affects, for example, Johnson County: https://www.johnson-county.com/dept_supervisors.aspx?id=18549
The county continues to recommend changes in the MW. It may be interesting to see if those also have an effect. I did not add them to our data. FYI @diegogentilepassaro @gabrieleborg

**Comment by santiagohermo** [comment]
It looks like we are missing some zipcodes in Oregon, where there are three MW: Portland, Portland Metro Area, Oregon State. We have no data for the Portland Metro Area. ([link 1](https://squareup.com/us/en/townsquare/your-guide-to-oregon-minimum-wage), [link 2](https://www.oregonlive.com/business/2017/07/oregon_minimum_wage_hike.html))

**Comment by santiagohermo** [comment]
I am done with the cities/counties. The number of MW increases quite a bit, from 171 to 308. What I did is the following:
- Add all MW changes in the [link](http://laborcenter.berkeley.edu/minimum-wage-living-wage-resources/inventory-of-us-city-and-county-minimum-wage-ordinances/) from the [opening comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/7#issue-575024319). For most of them I cross checked with city websites and Google
- From cities not in the link, I googled and extended the MW changes to present.

Question @gabrieleborg. For some places there are 3 or 4 MW according to firm size, but the excel only allows for 2 (places: Montgomery County, Novate, Saint Paul). Similarly, 1 county has a different MW for nonprofits, which is not in the columns (places: San Mateo). **If I add a column to the excel file for those categories, will the code brake?** Currently, I added them in available categories leaving a note.

**Comment by gabrieleborg** [comment]
Great! 

The code won't break, but your comment led me to reviewing it. I believe that as of now we are **actually using only the mw column**, the main minimum wage. you can see this in https://github.com/diegogentilepassaro/min_wage_rent/blob/4abb8c3c7daf1cd68ac21c9bd275c28aead141ee/base/code/substate_mw.do#L141

This however raised a more important issue. While at first I thought the min, mean , max mw were referred to the various mw for a given unit, it appears that in reality they just keep track of the time variation (e.g. if the mw changes for unit x on October 10, then the observation for x in October will have different min and max min wage).  In this sense, I believe we should only use max_mw, being the mw in place at the end of the month.

Conditional on checking that, we can then think how to use all these different mw!

**Comment by santiagohermo** [comment]
Thanks @gabrieleborg! Your comments make sense. Unless you disagree, I will:
1. Add a couple of columns to better reflect the different minimum wages within each place,
2. Make a small change to the code to use that information in a branch associated to this issue.

I will ping you so that you take a look at the code after I'm done.

We can use the branch to rebuild the datasets with the new mw data as well.

**Comment by santiagohermo** [comment]
In https://github.com/diegogentilepassaro/min_wage_rent/commit/abfdd0a349f397fb42786c74fcadc9d8c00ff031 I added the new mw variables and modified code to correctly compute min, mean and max MW.
It works fine in STATA. I couldn't run it via `make.py` though, because R's `RenameZillowVars_zipLevel.R` fails. I assume that's you changing the raw_data directory, @gabrieleborg

**Comment by diegogentilepassaro** [comment]
@gabrieleborg  and @santiagohermo I have completed the state changes in this task. Another useful source for reference is [this one](https://www.laborlawcenter.com/state-minimum-wage-rates/). Although the dates of enactment are not there it was still useful to see in which states there was changes. 

How should we proceed on this one now? 

@santiagohermo one quick question: in the substate changes that you added did you also added the ones that happened starting 2016 but that are not valid anymore ? This is for example the case of Louisville, KY

**Comment by santiagohermo** [comment]
That's great @gabrieleborg ! My rule was to add changes in the binding minimum wage. In the case of bans, if the change never became binding I didn't include it. If it did, but was banned later, I added a decrease in the MW to the state level on that date. For example, In Lexington Kentucky MW increased on 2016 July 1 to 8.2, and decreased back to the state's level on 2017 Jan 1 due to a state court ban.
Let me know if this is not what you had in mind!

Once you merge back #10 I will update this branch and run the analysis with our new data to check how everything looks. 👍

**Comment by gabrieleborg** [comment]
@santiagohermo @diegogentilepassaro I finally managed to check everything, and I reviewed #10 and make it work properly (there are only few minor changes that you should review). Once that is done let's go ahead and look how things turn out with the new periods!

Once we assess that new results make sense, we could close this making a note regarding a more careful analysis of the many different minimum wage maybe?

**Comment by santiagohermo** [comment]
After the merging of #10 (PR #14) I updated the branch and ran everything [setting dates to 31dec2019](https://github.com/diegogentilepassaro/min_wage_rent/commit/f356940eecc52600a8a9ed865da69bd1b4b507ba) (completing step 3), @gabrieleborg @diegogentilepassaro. [The results](https://github.com/diegogentilepassaro/min_wage_rent/tree/d68bf7a29c30f849b7a3cc3ba2559cbf8704178f/analysis/output) look even weirder than before.

My guess is that the sample is changing for those plots, but I haven't explored much into why the graphs look like that.

**Going forward**: 

I think this issue is completed, and I would move it to PR. We could randomly check some events added by each other @diegogentilepassaro. just to make sure we didn't miss anything.

However, if you want we can try to understand what is causing those jumpy plots, maybe ran everything again setting a date restriction or something.

**Comment by gabrieleborg** [comment]
we can PR for me, even though I also agree we should address once and for all those jumpy graphs.

**Comment by gabrieleborg** [comment]
I agree on going forward to PR. Also, I agree we should address the "jumpy plots" issue soon.

**Comment by santiagohermo** [comment]
Thread continues in #20
