### ISSUE TITLE
Produce slides for MVD Grad Workshop

### ISSUE THREAD

**Issue by diegogentilepassaro** [diegogentilepassaro/min_wage_rent#78]
[Goal]
Produce slides for MVD Grad Workshop

[Requirements]
Presentation is 20 minutes with 10 minutes more for questions.

**Comment by santiagohermo** [comment]
I updated the data section and now everything runs @diegogentilepassaro 

Tips:

- Simplify notes, and use \scriptize instead of \footnotesize

- Be careful when adding graphics. Use

```Latex
\includegraphics[width = \textwidth]{../../analysis/descriptive_maps/output/San_Diego_mw_msa.png}
```

instead of 
```Latex
\includegraphics[width = \textwidth]
			{../../analysis/descriptive_maps/output/San_Diego_mw_msa.png}
```

(in the paper we often use the bottom version)

- Just in case, avoid spaces in beginning or end of equations. Use `$i$` instead of `$ i$`

- Also be careful with math symbols. I found a typo (`\to` instead of `$\to$`)

- For clarity, remove caption and label of figures and motive title to title of frame

- Use `#` for Section, `##` for Subsection, and `###` for Frame. Example:
```R
# Data

## Minimum Wages

### Frame 1

Stuff 

- Element 1
- Element 2

### Frame 2

More stuff

$$y = x$$

```

- Finally, rewrite the empirical strategy section. It was really outdated (including trends, and not even mentioning strict exogeneity)

**Comment by santiagohermo** [comment]
Comments in the chat FYI @diegogentilepassaro @gabrieleborg 

[comentarios-presentacion-montevideo.txt](https://github.com/diegogentilepassaro/min_wage_rent/files/5719939/comentarios-presentacion-montevideo.txt)

**Comment by diegogentilepassaro** [comment]
Gracias @santiagohermo! Faltaron un par que agregué. 
[comentarios-presentacion-montevideo.txt](https://github.com/diegogentilepassaro/min_wage_rent/files/5719952/comentarios-presentacion-montevideo.txt)

**Comment by santiagohermo** [comment]
Summary: In this issue we prepared a short set of Slides for the MVD grad workshop. Edits were made directly to master. 

Feedback from presentation available [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/78#issuecomment-748506523)
